mongodb:
  image: mongo:3.0
  ports:
    - 27017:27017
  volumes:
    - /var/mongodb:/data/db
  command: "--smallfiles"

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - 5672:5672
    - 15672:15672
  volumes:
    - /var/lib/rabbitmq:/var/lib/rabbitmq
  hostname: sentinel

influxdb:
  image: tutum/influxdb
  ports:
    - 8083:8083
    - 8086:8086
    - 8090

api:
  image: numidiasoft/sentinel-api
  links:
    - mongodb
    - rabbitmq
    - influxdb
  ports:
    - 9292:9292
  volumes:
    - ./api:/app
    - /var/.api:/.bundle
  command: bash -c "bundle install --path=/.bundle && bundle exec shotgun config.ru --port=9292 -o 0.0.0.0"

cron:
  image: numidiasoft/sentinel-api
  volumes:
    - ./api:/app
    - /var/.cron:/.bundle
  links:
    - mongodb
    - rabbitmq
    - influxdb
  command: /cron

aggregator:
  image: numidiasoft/sentinel-api
  volumes:
    - ./api:/app
    - /var/.aggregator:/.bundle
  links:
    - mongodb
    - rabbitmq
    - influxdb
  command: bash -c "bundle install --path=/.bundle && bundle exec ruby ./bin/workers/aggregator"

alerts:
  image: numidiasoft/sentinel-api
  volumes:
    - ./api:/app
    - /var/.alerts:/.bundle
  links:
    - mongodb
    - rabbitmq
    - influxdb
  command: bash -c "bundle install --path=/.bundle && bundle exec ruby ./bin/workers/integration"

front:
  image: numidiasoft/sentinel-front
  volumes:
    - ./front/:/app
    - /var/node_modules:/app/node_modules
    - /var/bower_components:/app/bower_components
  ports:
    - 3000:3000
    - 3001:3001

