#!/bin/sh

docker run --rm -ti --name cron -v  /Users/tarik/projects/sentinel/api/:/app -v /var/.bundle:/.bundle  --link sentinel_mongodb_1:mongodb --link sentinel_rabbitmq_1:rabbitmq numidiasoft/sentinel-api:cron /bin/bash
