#!/bin/sh

docker rm window 2> /dev/null
docker run --rm -ti --name window  -v  /Users/tarik/projects/sentinel/api/:/app -v /var/.bundle:/.bundle  --link dev_mongodb_1:mongodb --link dev_rabbitmq_1:rabbitmq numidiasoft/sentinel-api:cron /bin/bash
