source 'https://rubygems.org'

gem 'rack'
gem 'pry'
gem 'activerecord'
gem 'mongoid'
gem 'puma'


gem 'grape'
gem 'roar'
gem 'grape-roar'

# http client
gem "faraday"

# pagination
gem 'kaminari'

# logging
gem 'grape_logging'

gem 'colorize'

gem 'rack-cors', :require => 'rack/cors'

gem 'bcrypt', '3.1.10', :require => 'bcrypt'
gem 'hashie'

group :development, :test do
  gem 'rb-fsevent'
  gem "rspec"
  gem 'factory_girl'
  gem 'rake'
  gem 'database_cleaner'
  gem 'vcr'
  gem 'webmock'
  gem 'rack-test'
  gem 'shotgun'
end
